services:
  server:
    build:
      context: .
    restart: unless-stopped
    ports:
      - '${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}'
    networks:
      - api-net
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://db:3306/${MYSQLDB_DATABASE}?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false'
      SPRING_DATASOURCE_USERNAME: '${MYSQLDB_USER}'
      SPRING_DATASOURCE_PASSWORD: '${MYSQL_PASSWORD}'
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy
  db:
    image: 'mysql:latest'
    restart: unless-stopped
    ports:
      - '${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}'
    expose:
      - '${MYSQLDB_LOCAL_PORT}'
    networks:
      - api-net
    environment:
      MYSQL_DATABASE: '${MYSQLDB_DATABASE}'
      MYSQL_USER: '${MYSQLDB_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQLDB_ROOT_PASSWORD}'
    volumes:
      - 'db_data:/var/lib/mysql'
    healthcheck:
      test:
        - CMD
        - pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
  phpmyadmin:
    image: 'phpmyadmin:latest'
    environment:
      PMA_HOST: db
      PMA_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    depends_on:
      - db
    links:
      - db
    ports:
      - '${PHP_MY_ADMIN_LOCAL_PORT}:${PHP_MY_ADMIN_DOCKER_PORT}'
    networks:
      - api-net
    restart: unless-stopped
volumes:
  db_data: null
networks:
  api-net: null
