name: 'spoty_app_web_debug'
services:
  app:
    container_name: 'rest_api'
    build:
      context: .
    restart: unless-stopped
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}
    networks:
      - api-net
    environment:
      POSTGRES_USER: '${POSTGRESQL_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://db:5432/${POSTGRESQL_DB}'
      SPRING_DATASOURCE_USERNAME: '${POSTGRESQL_USER}'
      SPRING_DATASOURCE_PASSWORD: '${POSTGRES_PASSWORD}'
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - static-files:/var/lib/opencore/static/uploads
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: 'database'
    image: 'postgres:alpine3.20'
    restart: unless-stopped
    ports:
      - ${POSTGRESQL_PORT_NUMBER}:${POSTGRESQL_PORT_NUMBER}
    expose:
      - ${POSTGRESQL_PORT_NUMBER}
    networks:
      - api-net
    environment:
      POSTGRES_DB: '${POSTGRESQL_DB}'
      POSTGRES_USER: '${POSTGRESQL_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1m
      timeout: 10s
      retries: 5

  pgadmin:
    container_name: 'pgadmin'
    image: 'elestio/pgadmin:latest'
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: '${ADMIN_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${POSTGRESQL_POSTGRES_PASSWORD}'
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '${PGADMIN_LOCAL_PORT}:${PGADMIN_DOCKER_PORT}'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - api-net

  mail:
    container_name: 'stalwart-mail'
    image: 'stalwartlabs/mail-server:latest'
    restart: unless-stopped
    ports:
      - "80:8080"
      - "443:443"
      - "25:25"
      - "587:587"
      - "465:465"
      - "143:143"
      - "993:993"
      - "4190:4190"
      - "110:110"
      - "995:995"
    volumes:
      - mail-data:/opt/stalwart-mail
    tty: true
    stdin_open: true
    networks:
      - api-net

  mail_test:
    image: 'axllent/mailpit:latest'
    container_name: 'mailpit'
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - api-net

volumes:
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local
  static-files:
    driver: local
  mail-data:
    driver: local

networks:
  api-net:
    driver: bridge
