version: '3.1'
services:
  app:
    build:
      context: .
    restart: unless-stopped
    ports:
      - '${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}'
    networks:
      - api-net
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mariadb://mariadb:3306/${MARIADB_DATABASE}?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false'
      SPRING_DATASOURCE_USERNAME: '${MARIADB_USER}'
      SPRING_DATASOURCE_PASSWORD: '${MARIA_PASSWORD}'
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    image: 'mariadb:latest'
    restart: unless-stopped
    ports:
      - '${MARIADB_LOCAL_PORT}:${MARIADB_DOCKER_PORT}'
    expose:
      - '${MARIADB_LOCAL_PORT}'
    networks:
      - api-net
    environment:
      MARIADB_ROOT_PASSWORD: '${MARIADB_ROOT_PASSWORD}'
      MARIADB_DATABASE: '${MARIADB_DATABASE}'
      MARIADB_USER: '${MARIADB_USER}'
      MARIADB_PASSWORD: '${MARIADB_ROOT_PASSWORD}'
    volumes:
      - 'mariadb_data:/var/lib/mysql'
      - 'mariadb_logs:/var/log/mysql'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-u", "root", "-p${MARIADB_ROOT_PASSWORD}" ]
      interval: 1m
      timeout: 10s
      retries: 5
  phpmyadmin:
    image: 'phpmyadmin:latest'
    environment:
      PMA_HOST: mariadb
      PMA_PASSWORD: '${MARIADB_ROOT_PASSWORD}'
    depends_on:
      mariadb:
        condition: service_healthy
    links:
      - mariadb
    ports:
      - '${PHP_MY_ADMIN_LOCAL_PORT}:${PHP_MY_ADMIN_DOCKER_PORT}'
    networks:
      - api-net
    restart: unless-stopped
volumes:
  mariadb_data:
    driver: local
  mariadb_logs:
    driver: local
networks:
  api-net: null
